name: Build & Deploy Web
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Shallow clone since we aren't running `nx affected`
          fetch-depth: 1

      - name: It works!
        run: echo "Build & Deploy Web works!"
