name: Build & Deploy Web
on:
  workflow_call:
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: build-web
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Shallow clone since we aren't running `nx affected`
          fetch-depth: 1
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      # TODO: nx computation caching?
      - name: Build apps/web
        run: npx nx run web:build:production

      # Upload build artifacts so it can be downloaded from a different job/workflow
      # since we can't define an approval step within a jobs step(s)...
      # i.e. to require approval for deploying to production
      # we have to use the `environment` property, which can only be used in a job
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-web-build
          path: ./dist/apps/web

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: deploy-staging-web
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-web-build
          path: ./dist

      - name: Deploy apps/web - Staging
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: ${{ github.event.repository.default_branch }}

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: deploy-production-web
    # use `environment: prod` to require an approval before
    # being able to run the job
    environment: prod
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-web-build
          path: ./dist

      - name: Deploy apps/web - Production
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './dist'
          production-branch: ${{ github.event.repository.default_branch }}
          production-deploy: true
