name: Build & Deploy Web
on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: build-web
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Shallow clone since we aren't running `nx affected`
          fetch-depth: 1
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Web
        run: npx nx run web:build
